---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - service

  broker:
    image: confluentinc/cp-kafka:6.2.1
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - service

  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - service

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - service

  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - service

  ## Eureka Server
  discovery-server:
    image: stonetone/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING.ZIPKIN.BASE-URL=http://zipkin:9411/
    depends_on:
      - zipkin
    networks:
      - service

  #MySQL for Player Service
  mySQL-player:
    container_name: mySQL-player
    image: mysql
    hostname: mySQLplayer
    environment:
      MYSQL_DATABASE: player-service
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
    - ./mysql_data_player:/var/lib/mysql
    networks:
      - service

    #MySQL for Team Service
  mySQL-team:
    container_name: mySQL-team
    image: mysql
    hostname: mySQLteam
    environment:
      MYSQL_DATABASE: team-service
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data_team:/var/lib/mysql
    networks:
      - service

  ## GateWay
  api-gateway:
    container_name: api-gateway
    build:
      context: /api-gateway
    ports:
      - "8181:8080"
    expose:
      - "8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
      - SPRING.ZIPKIN.BASE-URL=http://zipkin:9411/
    depends_on:
      - keycloak
      - discovery-server
      - zipkin
    networks:
      - service

  team-service:
    container_name: team-service
    build:
      context: /team-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mySQL-team:3306/team-service
      - SPRING.ZIPKIN.BASE-URL=http://zipkin:9411/
    depends_on:
      - discovery-server
      - api-gateway
      - mySQL-team
      - broker
      - zipkin
    networks:
      - service

  player-service:
    container_name: player-service
    build:
      context: /player-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mySQL-player:3306/player-service
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    depends_on:
      - discovery-server
      - api-gateway
      - mySQL-player
      - broker
      - zipkin
    networks:
      - service

networks:
  service:

