global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'team_service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['team-service:8080']
        labels:
          application: 'Team Service Application'
  -job_name: 'player_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      -targets: ['player-service:8080']
        labels:
          application: 'Player Service Application'